version: '2'

services:
    telegram-proxy:
        image: telegrammessenger/proxy:latest
        ports:
          - "443:443" #Proxy port, if you wish to change port - change left side 443 to another. Right side - it is port inside docker container
        volumes:
           - "proxy-config:/data"
        restart: unless-stopped
        env_file:
           - ./config.env
volumes:
  proxy-config:
