version: '2'

# Uncoment line if you want make any custom changes, if you want apply any environment change, uncoment "environment:" section too

services:
    telegram-proxy:
        image: telegrammessenger/proxy:latest
        ports:
          - "443:443" #Proxy port
          #- "2398:2398" # ONLY FOR TESTING - Show proxy stats on port 2398 outside of docker
        volumes:
           - "proxy-config:/data"
        restart: unless-stopped
        env_file:
           - ./config.env
volumes:
  proxy-config:
